# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3b17400b708980d890ca554f84f45fe3304436d316ba2a9ba33bbee1bb8881af3e798038c3c2281b357a3e3875f1eb6a8f0f28772f35f9dd0749f97c102e4bc

test:
  secret_key_base: 62b0cb1a1e4082b531f882760f7635d36e3775de9680f7520ef4d1c441aaf9a2dc0551b61fdbbe9d157c1aa1215b703a73a8f6af8ce6834d0b5d5d827c4365e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
